#!/bin/bash

DIRECTION=$1  # Expected: l or r

# Get active window address
active_addr=$(hyprctl activewindow -j | jq -r '.address')

# Get grouped array of the active window and its length
grouped=$(hyprctl activewindow -j | jq '.grouped')
length=$(echo "$grouped" | jq 'length')

echo $grouped, $length

# Get index of active window in group, 
# "null" if group is empty
index=$(echo "$grouped" | jq --arg addr "$active_addr" 'index($addr)')

echo $index

# If index is null (grouped length = 0)
if [[ -z "$index" || "$index" == "null" || "$length" -eq 0 ]]; then
  hyprctl dispatch movefocus "$DIRECTION"
  hyprctl dispatch alterzorder top
  exit 0
fi

# Edge cases
if [[ "$DIRECTION" == "l" && "$index" -eq 0 ]]; then
  hyprctl dispatch movefocus l
  hyprctl dispatch alterzorder top
  exit 0
fi

if [[ "$DIRECTION" == "r" && "$index" -eq $((length - 1)) ]]; then
  hyprctl dispatch movefocus r
  hyprctl dispatch alterzorder top
  exit 0
fi

# Inside group, move within group
if [[ "$DIRECTION" == "l" ]]; then
  hyprctl dispatch changegroupactive b
elif [[ "$DIRECTION" == "r" ]]; then
  hyprctl dispatch changegroupactive f
fi
